### ISSUE TITLE
Docker Image won't connect to External RDM Database

### ISSUE THREAD

**Issue by zack-kyria** [PickleRickVE/RealDeviceMap-tools#24]
My docker-compose.yml:

 ```
atlas-tools:
    image: ghcr.io/picklerickve/realdevicemap-tools:master
    container_name: atlas-rdmtools
    networks:
      - atlas-network
   # depends_on:
   #   - atlas-rdm
    restart: unless-stopped
    environment:
      DB_HOST: host.docker.internal
      DB_NAME: rdmdb
      DB_PORT: 3306
      DB_USER: zaxos
      DB_PSWD: XXXXX
     # MDB_ACTIVE: true
     # MDB_HOST: host.docker.internal
     # MDB_NAME: manualdb
     # MDB_PORT: 3306
     # MDB_USER: root
     # MDB_PSWD: XXXXX
     # OWN_TS: https://IP:PORT/tile/STYLE/{z}/{x}/{y}/1/png
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./tools/config/docker-php-maxexectime.ini:/usr/local/etc/php/conf.d/docker-php-maxexectime.ini
      # - ./tools/config/.htpasswd:/var/www/html/config/.htpasswd # Initial username/password is admin/admin
      # - ./tools/config/.htaccess:/var/www/html/.htaccess
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - 9100:80
```

And i am getting the following error during the startup:

```
atlas-rdmtools  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.23.0.2. Set the 'ServerName' directive globally to suppress this message
atlas-rdmtools  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.23.0.2. Set the 'ServerName' directive globally to suppress this message
atlas-rdmtools  | [Mon Mar 20 00:12:26.400182 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.2 configured -- resuming normal operations
atlas-rdmtools  | [Mon Mar 20 00:12:26.400240 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

```
